global using Autofac;
global using Autofac.Core;
global using Autofac.Core.Activators.Reflection;
global using Autofac.Features.Variance;
global using Dapper;
global using FluentValidation;
global using MediatR;
global using MediatR.Pipeline;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using OrderManagement.BuildingBlocks.Application;
global using OrderManagement.BuildingBlocks.Application.Data;
global using OrderManagement.BuildingBlocks.Application.Emails;
global using OrderManagement.BuildingBlocks.Application.Events;
global using OrderManagement.BuildingBlocks.Application.Outbox;
global using OrderManagement.BuildingBlocks.Infrastructure;
global using OrderManagement.BuildingBlocks.Infrastructure.DomainEventsDispatching;
global using OrderManagement.BuildingBlocks.Infrastructure.Emails;
global using OrderManagement.BuildingBlocks.Infrastructure.EventBus;
global using OrderManagement.BuildingBlocks.Infrastructure.InternalCommands;
global using OrderManagement.BuildingBlocks.Infrastructure.Serialization;
global using OrderManagement.Modules.UserAccess.Application.Configuration.Commands;
global using OrderManagement.Modules.UserAccess.Application.Contracts;
global using OrderManagement.Modules.UserAccess.Domain.Users;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.DataAccess;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Email;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.EventsBus;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Logging;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Mediation;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Processing;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Processing.Inbox;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Processing.InternalCommands;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Processing.Outbox;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Quartz;
global using OrderManagement.Modules.UserAccess.Infrastructure.Configuration.Security;
global using OrderManagement.Modules.UserAccess.Infrastructure.Domain.Users;
global using OrderManagement.Modules.UserAccess.Infrastructure.InternalCommands;
global using OrderManagement.Modules.UserAccess.Infrastructure.Outbox;
global using Polly;
global using Quartz;
global using Quartz.Impl;
global using Quartz.Logging;
global using Serilog.Core;
global using Serilog.Events;
global using System.Collections.Concurrent;
global using System.Collections.Specialized;
global using System.Reflection;
global using System.Security.Cryptography;
global using System.Text;
global using ICommandsScheduler = OrderManagement.Modules.UserAccess.Application.Configuration.Commands.ICommandsScheduler;
global using ILogger = Serilog.ILogger;
global using Logger = Quartz.Logging.Logger;
global using LogLevel = Quartz.Logging.LogLevel;
global using Module = Autofac.Module;
global using TriggerBuilder = Quartz.TriggerBuilder;